server:
  port: 8080

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://:3306/urban
      driver-class-name: org.mariadb.jdbc.Driver
      username: urban
      password: "urban#123"
      maximum-pool-size: 5
      pool-name: "URBAN-DB-POOL"
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    mode: HTML
    cache: false
